config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#index'
  resources :pages
  
  resources :rooms do
    resources :messages
  end

  root "home#index"
  
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show]

  devise_scope :user do
    get "users" => "devise/sessions#new"
  end

end

app/views/shared/_flash.html.erb
<div id="messagesContainer">
 
  <% flash.each do |type, msg|%>   
    <%= content_tag :div, msg, class: build_alert_classes(type) do%>
      <button><span>&times;</span></button>
      <%= msg %>
    <% end %>
  <% end %>
</div>

 

app/views/shared/_head.html.erb
 <title>TheDummyProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css"
      integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY="
      crossorigin="anonymous"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.4.0/tailwind.min.css"
      integrity="sha256-CAI/7ThhltsmP2L2zKBYa7FknB3ZwFbD0nqL8FCdxdc="
      crossorigin="anonymous"/>

     <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>


    <script src="https://unpkg.com/flowbite@1.5.5/dist/datepicker.js"></script>

app/views/shared/_navbar.html.erb
  <nav class="flex items-center bg-gray-800 p-2 flex-wrap">
  <li><%= link_to 'The Dummy Project', root_path, class: "text-xl text-white font-bold uppercase tracking-wide" %></li>
  
    <button
      class="text-white inline-flex p-3 hover:bg-gray-900 rounded lg:hidden ml-auto hover:text-white outline-none nav-toggler"
      data-target="#navigation"
    >
      <i class="material-icons">menu</i>
    </button>
    <div
      class="hidden top-navbar w-full lg:inline-flex lg:flex-grow lg:w-auto"
      id="navigation"
    >
      <div
        class="lg:inline-flex lg:flex-row lg:ml-auto lg:w-auto w-full lg:items-center items-start flex flex-col lg:h-auto"
      >


      <%= render "search/form" %>
      <%= link_to "Pages", pages_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
           
      <% if !current_user.guest? %>       
        <%= link_to "Search", search_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
        <%= link_to "Profile", edit_user_registration_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
      <% else %>
        <%= link_to "Dummy", root_path, class:"lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
        <%= link_to "Login", new_user_session_path, data: { turbo_frame: 'modal' }, class: "lg:inline-flex lg:w-auto w-full px-3 py-2 rounded text-gray-400 items-center justify-center hover:bg-gray-900 hover:text-white" %>
      <% end %>
      </div>
    </div>
  </nav>

  
 
  
  