config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#index'
  resources :pages
  
  resources :rooms do
    resources :messages
  end

  root "home#index"
  
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show]

  devise_scope :user do
    get "users" => "devise/sessions#new"
  end

end

app/views/pages/_test.html.erb
<h1>Working</h1>

app/views/pages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing page</h1>

  <%= render "form", page: @page %>

  <%= link_to "Show this page", @page, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pages", pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pages/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pages</h1>
    <%= link_to 'New page', new_page_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pages" class="min-w-full">
    <% for page in current_user.pages %>
    <%= page.first_name %>
    <%= link_to "Show this page", page, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/pages/new.html.erb
  <h1 class="font-bold text-4xl">New page</h1>
  <%= link_to 'Back to pages', pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", page: @page %>

  
</div>

app/views/pages/show.html.erb
<% if @page # @page.page_type == "as" %>
  <%= render @page %>
<% else %>
  <%= render 'test' %>
<% end %>